export const posts = [
  {
    id: "1",
    createdAt: "today",
    title: "Title 1",
    published: true,
    author: "user-1",
  },
  {
    id: "2",
    createdAt: "today",
    title: "Title 2",
    published: true,
    author: "user-1",
  },
  {
    id: "3",
    createdAt: "today",
    title: "Title 3",
    published: true,
    author: "user-1",
  },
  {
    id: "4",
    createdAt: "today",
    title: "Title 4",
    published: true,
    author: "user-1",
  },
  {
    id: "5",
    createdAt: "today",
    title: "Title 5",
    published: true,
    author: "user-1",
  },
  {
    id: "6",
    createdAt: "today",
    title: "Title 6",
    published: true,
    author: "user-1",
  },
  {
    id: "7",
    createdAt: "today",
    title: "Title 7",
    published: true,
    author: "user-1",
  },
  {
    id: "8",
    createdAt: "today",
    title: "Title 8",
    published: true,
    author: "user-1",
  },
  {
    id: "9",
    createdAt: "today",
    title: "Title 9",
    published: true,
    author: "user-1",
  },
];
